### ISSUE TITLE
code review for ian c. 

### ISSUE THREAD

**Issue by sidrathabib** [hunter-classes/spring-2022-135-lab-07-ianclarke03#2]
- in regard of bad-code.cpp, just for future reference, try to add a second test just to assure the efficiency of the code
- add comments to improve and add organization to the syntax of your code
- .h files match .cpp files 
- code's functional

**Comment by ianclarke03** [comment]
That's a good idea. My code easily gets messy and all over the place, and I think comments will help out. Thanks!
